### ISSUE TITLE
Error handling for OpRouteAbbrev

### ISSUE THREAD

**Issue by alexmarc-us** [FerryTempo/FTServer#18]
See https://github.com/FerryTempo/FTServer/blob/main/src/FerryTempo.js#L77

**Comment by ckulfan** [comment]
According to the [WSDOT API documentation](https://www.wsdot.wa.gov/ferries/api/vessels/documentation/rest.html) this array can be empty. This should only happen when the boat is not in service, so we will check this and print an error message if not. Otherwise, we will treat and empty array as the same as being out of service.

**Comment by ckulfan** [comment]
Upon looking at the code, we already have a check to ensure we properly handle the case where the list of routes is empty:
if (InService && routeAbbreviation && routeFTData[routeAbbreviation] && routePositionData[routeAbbreviation])

So, I will add error checking and reporting just so we can know if we ever get more than one route and/or an empty list when the boat is in service.

**Comment by ckulfan** [comment]
This has been resolved with the latest push of code
